import { PERMISSIONS, type PermissionKey } from "./catalog";

/** Papéis-base sugeridos no seed. Totalmente editável depois pelo administrador. */
export const SYSTEM_ROLE_DEFAULTS: Record<string, PermissionKey[] | "*"> = {
  Administrador: "*",
  Gestor: [
    "contacts:view_all",
    "contacts:create",
    "contacts:update",
    "contacts:reassign",
    "properties:view",
    "properties:update",
    "owners:view",
    "matches:view",
    "matches:recalculate",
    "visits:view",
    "visits:view_all",
    "visits:update",
    "visits:cancel",
    "visits:reassign",
    "visits:override_conflict",
    "tasks:view",
    "tasks:view_all",
    "tasks:create",
    "tasks:update",
    "tasks:complete",
    "tasks:cancel",
    "tasks:reassign",
    "proposals:view",
    "reports:view",
    "automations:manage",
    "imports:view",
    "imports:create",
    "imports:execute",
    "imports:update_existing",
    "imports:create_duplicate",
    "imports:rollback",
    "imports:view_sensitive_data",
    "users:view",
    "roles:view",
    "permissions:view",
  ],
  Corretor: [
    "contacts:view_own",
    "contacts:create",
    "contacts:update",
    "contacts:view_financial",
    "properties:view",
    "properties:create",
    "properties:update",
    "owners:view",
    "owners:create",
    "matches:view",
    "matches:recalculate",
    "visits:view",
    "visits:create",
    "visits:update",
    "visits:cancel",
    "visits:override_conflict",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:complete",
    "tasks:cancel",
    "proposals:view",
    "proposals:create",
    "proposals:update",
    "reports:view",
    "imports:view",
    "imports:create",
    "imports:execute",
    "imports:view_sensitive_data",
  ],
  Assistente: [
    "contacts:view_all",
    "contacts:create",
    "properties:view",
    "properties:update",
    "matches:view",
    "visits:view",
    "visits:create",
    "tasks:view",
    "tasks:create",
    "tasks:update",
    "tasks:complete",
  ],
};

export function resolveRolePermissions(role: keyof typeof SYSTEM_ROLE_DEFAULTS): PermissionKey[] {
  const value = SYSTEM_ROLE_DEFAULTS[role];
  if (value === "*") return PERMISSIONS.map((p) => p.key);
  return value ?? [];
}
